apiVersion: v1
data:
  kube-config: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1EUXdOakUwTVRnME4xb1hEVE14TURRd05URTBNVGcwTjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk5PCisyM3FkdC9vV0YvSHkrNUxkR1VhRm1RanRzZWloRXlXaDVJd21VQ09vSzh6Z3gvcFA2MGhrTEdOQUkyZUIzMEkKQnc3eDBzWlR0ZWxyTnU1MWc1UzdSRm5kajE1VVFLLy9kSEV3a0ZmbGE0QmI5S1J1Vmh0VDNWc0w5ZkU0RW5RSQp5Yk42TFYyendrZmJFM2Q1L3hQNkowaEFDQ20yMWhOYjBrTkRZZ1M0ZGEvUDFpV1YyaU1HWGg1b2dReENuNXRiCjJ2UTk3c1A2U3FTZ1RsNUwwYm8wcHUrUkRXL3Y4aXBPZWJDVHJuOVV2QjhSRnVxTUJQbjFJaXdYeTBCZFcyNmwKdi9qdjBldytSY2lQaXVRcXVMMDFxKzZzY3N2c2R5cE5lLzVXcHo0dXh6ZGZKaHZQVWUvVlBoVjUrL1c3WUx0NwpVWnlOL1FWem0wK3I2dVpYNUZNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSS3l1RDdHMWJYNjc1Sk9PMm5GWkFFSlJVTTlEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFyZmkyR0JYdwoyb1hTRFdIWXhIN3Fmc0dQaHhaQlpXSVE2dnFpTXZqUEJKbS9LSENWdzRIcGN1WTFmVjdBcVY3aVpoeGp6ODI5ClJ0aXVIdmxkamlwS21EUHJWSzVpdXZQVnRLM3RGYjFwL2FBVXdiN2hIL2FmNUxNVVpXdUd2MStsUkM0R3YwWjIKamxDRmJCbmF2dnErN0U2S29VaWkycGpQSmozbTNsUHc0ZWUxMmhkb2hjNUpiL0RjOGFwWGNMWm4rM21zQS9HQgo4VmNDMHhZQVR0dndybHBRQ0JGNmpXS3pXR05wTG5tZTRoOWsxZFBBSCtEZVlHeEpGVUZMRHpLTXJpYnpzaXhJCmtKTEljWmlYbStPbVk0d3hrUk4xd21oUnZSOXZIZ3cyUjdCUTJzR2FMdW5EUEkrUUJyQ0IzSmNWbEphS0JDZjkKYUF2MWgxczhjcHIzWkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
        extensions:
        - extension:
            last-update: Mon, 15 Nov 2021 13:10:39 CET
            provider: minikube.sigs.k8s.io
            version: v1.23.2
          name: cluster_info
        server: https://192.168.49.2:8443
      name: minikube
    contexts:
    - context:
        cluster: minikube
        extensions:
        - extension:
            last-update: Mon, 15 Nov 2021 13:10:39 CET
            provider: minikube.sigs.k8s.io
            version: v1.23.2
          name: context_info
        namespace: orange
        user: minikube
      name: minikube
    current-context: minikube
    kind: Config
    preferences: {}
    users:
    - name: minikube
      user:
          token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5xQzFsbkhKMnJsczdpTDZDNEFuTzFveTA5V2ptYlVmQ1dCSHZmTk01TkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcmFuZ2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiamVua2lucy10b2tlbi1sNXhzayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjJmNTIzMDctNTU0YS00NGJlLWI3ZDYtN2MzZTEyZDg1MjczIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om9yYW5nZTpqZW5raW5zIn0.TUW6XMRpNmYe0rOYSEVs-Ish4eZ9z50oM-1y7Wge52hd4zd9slWHDjQwc3hwJI6wHPup_optA5uIyZ36cVjnSMHiwfwWUj2lg4ScZOJmpcWqErAS9WRcXePvRaYxvtgNkMV3QpSPlTjAwCrmHoS4K1vvG9cgJS2G3BHkg6pQZQ2mQ3h9nOyuT3t1C5_3Op2fPt-bxXh9J9TiCp8uMfj-gJG797hPtqjcVZu5HTsUuB72G_ru5SwCXm-Me7ZlbIVhvihSc4_2z5v7BRD3lxKW5jXnKEGSmjICwW9plgeXLmtdHsBuNGcPNHMV2bKoyjrUK9_RKj5zziAouujq5e8E6Q
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: orange
