apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jenkins
  name: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      containers:
      - image: jenkins-orange:0.0.2
        imagePullPolicy: IfNotPresent
        name: jenkins-orange
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home/.kube/config
          name: config
          subPath: kube-config
        - mountPath: /var/jenkins_home/jenkins.yaml
          name: config
          subPath: jenkins.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: jenkins-config
        name: config