apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jenkins
  name: jenkins
  namespace: orange
spec:
  containers:
  - image: jenkins-orange:0.0.2
    imagePullPolicy: Never
    name: jenkins
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/jenkins_home/.kube/config
      name: config
      subPath: kube-config
    - mountPath: /var/jenkins_home/jenkins.yaml
      name: config
      subPath: jenkins.yaml
  volumes:
  - name: config
    configMap:
      name: jenkins-config